export const productos = [
    { id: 1, nombre: "Pescado frito con papas fritas", precio: 100000, imagen: '/productos/pescado_frito_con_papas_fritas.png' },
    { id: 2, nombre: "Ceviche de pescado", precio: 200000, imagen: '/productos/ceviche_de_pescado.png'  },
    { id: 3, nombre: "Ceviche de champiñon", precio: 150000, imagen: '/productos/ceviche_de_champiñon.png'  },
    { id: 4, nombre: "Machas a la parmesana", precio: 120000, imagen: '/productos/machas_a_la_parmesana.png'  },
    { id: 5, nombre: "Mariscal Pearl´s", precio: 100000, imagen: '/productos/mariscal_pearls.png' },
    { id: 6, nombre: "Salmon con ensaladas", precio: 120000, imagen: '/productos/salmon_con_ensaladas.png'  },
    { id: 7, nombre: "Tabla afrodisiaca", precio: 200000, imagen: '/productos/tabla_afrodisiaca.png'  },
    { id: 8, nombre: "Levanta muertos", precio: 150000, imagen: '/productos/levanta_muertos.png'  },
    { id: 9, nombre: "Jugo de piña", precio: 50000, imagen: '/productos/jugo_de_piña.png'  },
    { id: 10, nombre: "Jugo de frutilla", precio: 50000, imagen: '/productos/jugo_de_frutilla.png'  },
    { id: 11, nombre: "Vino tinto", precio: 150000, imagen: '/productos/vino_tinto.png'  },
    { id: 12, nombre: "Vino blanco", precio: 150000, imagen: '/productos/vino_blanco.png'  },
    { id: 13, nombre: "Vino rosa", precio: 150000, imagen: '/productos/vino_rosa.png'  },
    { id: 14, nombre: "Espumante rosa", precio: 120000, imagen: '/productos/espumante_rosa.png'  },
    { id: 15, nombre: "Cafe con frutilla", precio: 70000, imagen: '/productos/cafe_con_frutilla.png'  },
    { id: 16, nombre: "Cafe con crema", precio: 70000, imagen: '/productos/cafe_con_crema.png'  },
    { id: 17, nombre: "Copa helado 3 leches", precio: 60000, imagen: '/productos/copa_helado_3_leches.png'  },
    { id: 18, nombre: "Copa helado chocolate", precio: 60000, imagen: '/productos/copa_helado_chocolate.png'  },
    { id: 19, nombre: "Ferrero rocher", precio: 200000, imagen: '/productos/ferrero_rocher.png'  },
    { id: 20, nombre: "Bombones La fete", precio: 200000, imagen: '/productos/bombones_la_fete.png'  },
    { id: 21, nombre: "Frutillas con chocolate", precio: 150000, imagen: '/productos/frutillas_con_chocolate.png'  },
    { id: 22, nombre: "Cajita sorpresa La fete rosa", precio: 3000000, imagen: '/productos/cajita.png'  }
];